//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookservice
    {
        public Bookservice()
        {
            this.GenerateReports = new HashSet<GenerateReport>();
            this.GenerateReports1 = new HashSet<GenerateReport>();
            this.Payments = new HashSet<Payment>();
            this.Payments1 = new HashSet<Payment>();
        }
    
        public int ServiceId { get; set; }
        public string Address { get; set; }
        public string NumberOfAC { get; set; }
        public string TypesOfAC { get; set; }
        public Nullable<int> TypesOfService { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> AssignedTechnician { get; set; }
        public Nullable<int> ServiceStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Service Service1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<GenerateReport> GenerateReports { get; set; }
        public virtual ICollection<GenerateReport> GenerateReports1 { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Payment> Payments1 { get; set; }
    }
}
