//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bookservices = new HashSet<Bookservice>();
            this.Bookservices1 = new HashSet<Bookservice>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Feedbacks1 = new HashSet<Feedback>();
            this.GenerateReports = new HashSet<GenerateReport>();
            this.GenerateReports1 = new HashSet<GenerateReport>();
            this.GenerateReports2 = new HashSet<GenerateReport>();
            this.GenerateReports3 = new HashSet<GenerateReport>();
            this.Packages = new HashSet<Package>();
            this.Packages1 = new HashSet<Package>();
            this.Payments = new HashSet<Payment>();
            this.Payments1 = new HashSet<Payment>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public string ResetPasswordCode { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
    
        public virtual ICollection<Bookservice> Bookservices { get; set; }
        public virtual ICollection<Bookservice> Bookservices1 { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Feedback> Feedbacks1 { get; set; }
        public virtual ICollection<GenerateReport> GenerateReports { get; set; }
        public virtual ICollection<GenerateReport> GenerateReports1 { get; set; }
        public virtual ICollection<GenerateReport> GenerateReports2 { get; set; }
        public virtual ICollection<GenerateReport> GenerateReports3 { get; set; }
        public virtual ICollection<Package> Packages { get; set; }
        public virtual ICollection<Package> Packages1 { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Payment> Payments1 { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual UserType UserType1 { get; set; }
    }
}
