--MATH FUNCTION
use MadanMohan342;

-- 1. POWER(NUM1,NUM2) USED TO GET THE VALUE NUM1^NUM2
SELECT POWER(2,3) AS 'VALUE OF 2 POWER 3';

-- 2. SUM(COLUMN_NAME) USED TO SUM THE VALUES
SELECT SUM(MDEmployeeSalary) AS 'SUM OF GIVEN VALUES' FROM MDEmployee;

-- 3. COUNT(COLUMN_NAME) USED TO COUNT THE NO. OF COLUMNS IN A TABLE
SELECT COUNT(MDEmployeeID) AS 'NO. OF EMPLOYEE' FROM MDEmployee;

-- 4. MAX(COLUMN_NAME) USED TO FIND THE MAXIMUM VALUE FROM THE COLUMN OF TABLE
SELECT MAX(MDEmployeeSalary) FROM MDEmployee
