
--OTHER FUNCTIONS

SELECT CAST(200.234 AS INT) --IS USED TO CONVERT ONE DATATYPE INTO ANOTHER DATATYPE

SELECT CURRENT_USER --IS USED TO GET THE CURRENT USER IN THE SYSTEM, IN MY CASE IT IS dbo

SELECT IIF(1<3,'GREATER','SMALLER'); --IS USED TO RETURN GREATER IF SPECIFIED CONDITION IS TRUE OTHERWISE SMALLER

SELECT ISNULL(NULL,'MOHAN DAS'); --IS USED TO CHECK THE NULL VALUE AND REPLACE IT WITH THE SPECIFIED STRING

SELECT SYSTEM_USER; --IS USED TO GET THE SYSTEM USER

SELECT SESSION_USER; --IS USED TO GET THE SESSION USER

DBCC CHECKIDENT(orders)  --IS USED TO CHECK THE IDENTITY (AUTO INCREAMENT VALUE) OF THE TABLE
DBCC CHECKIDENT(orders, RESEED, numberStartsWith) --WE SPECIFY THE NUMBER, THE VALUE START FROM