USE MadanMohan342;
-- 1. SUBSTRING('STRING',START,LENGTH) position start with 1
SELECT SUBSTRING('MOHAN DAS',7,3);

-- 2. LEN('STRING') IS USED TO FIND THE LENGTH OF THE STRING
SELECT LEN('SQL ASSIGNEMNT') AS ' LENGTH OF STRING';

-- 3. LOWER('STRING') IS USED TO CONVERT THE STRING INTO LOWER CASE
SELECT LOWER('SQL SESSION') AS 'LOWERCASE';

-- 4. UPPER('STRING') IS USED TO CONVERT THE STRING INTO UPPER CASE
SELECT UPPER('sql Session') AS 'UPPERCASE';

-- 5. REVERSE('STRING') IS USED TO REVERSE THE GIVEN STRING
SELECT REVERSE('Shaligram Infotech') AS 'REVERSE';

-- 6. TRIM('STRING') IS USED TO REMOVE THE SPACES FROM BEGINNING AND END
SELECT TRIM('   MOHAN    ') AS 'TRIM';

-- 7. LTRIM('STRING') IS USED TO REMOVE THE SPACES FROM BEGINNING
SELECT LTRIM('   MOHAN') AS 'TRIM';

-- 8. RTRIM('STRING') IS USED TO REMOVE THE SPACES FROM END
SELECT RTRIM('MOHAN    ') AS 'TRIM';

-- 9. REPLACE('STRING','','') IS USED TO REPLACE THE CHARACTER IN A STRING
SELECT REPLACE('MOHAN DAS','DAS','KUMAR') AS 'REPLACE'; -- REPLACE 'DAS' WITH 'KUMAR'

-- 10. CONCAT('STRING1','STRIN2') JOIN BOTH THE STRING
SELECT CONCAT('SQL','ASSIGNMENT') AS 'CONCAT';

-- 11. CONCAT_WS('SEPERATOR','STRING1','STRING2') JOIN BOTH THE STRING WITH SOME SEPARATOR
SELECT CONCAT_WS('#','MOHAN','MIHIR','SHASHANK')

-- 12. LEFT('STRING',LENGTH) USED TO GET THE LENGTH OF CHARACTER FROM THE LEFT OF THE STRING
SELECT LEFT('SHALIGRAM INFOTECH',5) AS 'LEFT';

-- 13. RIGHT('STRING',LENGTH) USED TO GET THE LENGTH OF CHARACTER FROM THE RIGHT OF THE STRING
SELECT RIGHT('SHALIGRAM INFOTECH',5) AS 'RIGHT';

-- 14. STUFF('STRING',START,END,'STRING') USED TO REPLACE THE PART OF THE STRING WITH THE GIVEN STRING
SELECT STUFF('JAVASCRIPT TUTORIAL',1,10,'mohan') AS 'STUFF'; --FROM THE STRING, FROM LENGTH 1 TO 10 REPLAE IT WITH STRING SQL

-- 15. ASCII('CHARACTER') USED TO GET THE ASCII VALUE OF THE CHARACTER SPECIFIED
SELECT ASCII('M') AS 'ASCII';

-- 16. CHAR(INTEGER) USED TO GET THE CHARACTER OF THE SPECIFIED ASCII CODE OF THE CHARACTER
SELECT CHAR(65) AS 'CHAR';